### ISSUE TITLE
Recreate containers when Redis is out of space 

### ISSUE THREAD

**Issue by satoshinotdead** [Metastem/wikiless#113]
I wonder the simplest method to recreate the Redis on Wikiless container if it's gets out of space _(limited within `docker-compose.yml` file)_.

I'm refering specifically to the `tmpfs` size limit. I get `SERVER_ERROR_REDIS_SET` when it's full and I want to recreate this container in order to not block our instance because of that.

Please ask me any questions. Thanks!

**Comment by xbdmHQ** [comment]
> I wonder the simplest method to recreate the Redis on Wikiless container if it's gets out of space _(limited within `docker-compose.yml` file)_.
> 
> I'm refering specifically to the `tmpfs` size limit. I get `SERVER_ERROR_REDIS_SET` when it's full and I want to recreate this container in order to not block our instance because of that.
> 
> Please ask me any questions. Thanks!

To fix the ```SERVER_ERROR_REDIS_SET``` error when using Redis in a Docker environment, here are some potential solutions based on the available information:

Ensure the Redis container is running correctly:

Check the status of the Redis container using docker ps. The container should be in a running state.

Verify the Redis port mapping:

Ensure that the Redis port (typically 6379) is correctly mapped from the container to the host machine. This can be done by inspecting the container's port mapping or using the docker inspect command. 


Check the Redis configuration:

If you are using a custom Redis configuration file, ensure that the file is correctly mounted into the Redis container and that the configuration settings are correct. 


Set the Redis password (if required):

If your Redis instance requires a password, make sure to provide the correct password in your application's connection string. You can also set the password when starting the Redis container by adding the --requirepass option to the redis-server command. 


Increase the Redis memory limit (if necessary):

If the ```SERVER_ERROR_REDIS_SET``` error is related to memory issues, you can try increasing the Redis memory limit by setting the vm.overcommit_memory system parameter to 1. 


Use the correct Redis connection string:

Ensure that your application is connecting to the Redis container using the correct hostname or IP address. Instead of using localhost or 127.0.0.1, try using the container name or the Docker network alias (e.g., redis) if you're using Docker Compose. 


Add a health check for the Redis container:

Implement a health check in your Docker Compose file or Kubernetes manifest to ensure the Redis container is ready to accept connections before your application tries to connect. This can help prevent connection issues.
