### ISSUE TITLE
Search doesn’t work in non-English

### ISSUE THREAD

**Issue by lenwar** [Metastem/wikiless#24]
It seems that the search function is broken in the non-English wikiless pages. When I try to search on the Dutch page, I get redirected to the English main page. (So not even to the Search Results special page, but the ‘Front page/Main Page’

**Comment by static000** [comment]
This issue should be fixed by #14. Can you confirm that the instance you are using has the latest version of Wikiless deployed? A simple way of checking this is to go to the main page of the instance, open developer console and execute following command:

`document.querySelector('input[name="lang"]') != null`

If the result is `false`, then the instance you are using is outdated. For example, [wikiless.org](https://wikiless.org) is outdated, while [wikiless.esmailelbob.xyz](https://wikiless.esmailelbob.xyz) includes the fix.

**Comment by xbdmHQ** [comment]
> It seems that the search function is broken in the non-English wikiless pages. When I try to search on the Dutch page, I get redirected to the English main page. (So not even to the Search Results special page, but the ‘Front page/Main Page’

its open source, provide dutch translation to the developer and he can fix it

**Comment by lenwar** [comment]
> > It seems that the search function is broken in the non-English wikiless pages. When I try to search on the Dutch page, I get redirected to the English main page. (So not even to the Search Results special page, but the ‘Front page/Main Page’
> 
> 
> 
> its open source, provide dutch translation to the developer and he can fix it

I don't think a functional error will be fixed by translating something.

**Comment by xbdmHQ** [comment]
Oh my bad read too fast
