### ISSUE TITLE
Add instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Metastem/wikiless#30]
@Metastem I think I have full right to say my point of view about it, you give me ZERO chances. About the why I did it, look at my reply: https://codeberg.org/LibRedirect/libredirect/issues/89#issuecomment-919797

I'm waiting your reply about it

**Comment by Metastem** [comment]
Sorry, we generally oppose and suppress dissidents to all religions in the world. Freedom of speech is not our principle. Freedom of speech is only something defined by authority and used to enslave the proletariat. True freedom is won by continuous revolution.  , and what religion maintains is only the old system and the old feudal exploitation system, which is launched.  We'll keep your instance, but we'll flag it with a warning.  Please stop starting wars, there is no war, only class struggle.

**Comment by Metastem** [comment]
![k eUC0ss2ZqV-Iw HhhH7g_b](https://github.com/Metastem/wikiless/assets/110768529/d2004ae8-e434-42d1-a464-209496558c3b)

**Comment by EsmailELBoBDev2** [comment]
> Sorry, we generally oppose all religions in the world. Freedom of speech is not our principle. Freedom of speech is only something defined by authority and used to enslave the proletariat. True freedom is won by continuous revolution. , while religion only upholds the old system and the old feudal exploitation system, which is reactionary. We'll keep your instance, but we'll flag it with a warning.

Look I know no matter what I say your point of view won't change but who told you religion is old? They keep discover new stuff in science that is already told MANY years ago in Islam. Did you know way way back in Islam, earth shape was said to be look like circle not flat, before science discovers it. Research before you talk and look like a dumb.

**Comment by Metastem** [comment]
> > Sorry, we generally oppose all religions in the world. Freedom of speech is not our principle. Freedom of speech is only something defined by authority and used to enslave the proletariat. True freedom is won by continuous revolution. , while religion only upholds the old system and the old feudal exploitation system, which is reactionary. We'll keep your instance, but we'll flag it with a warning.
> 
> Look I know no matter what I say your point of view won't change but who told you religion is old? They keep discover new stuff in science that is already told MANY years ago in Islam. Did you know way way back in Islam, earth shape was said to be look like circle not flat, before science discovers it. Research before you talk and look like a dumb.

Religion is based primarily on faith, not reason: one chooses to believe in God and to entertain other religious ideas that, almost by definition, cannot be demonstrated, tested, corroborated, or proven. A central part of the struggle of anarchists is the struggle for reason. The liberated society, to the anarchist thinkers, represents the triumph of reason, and the complete triumph of reason entails the elimination/destruction of non-rational beliefs, such as superstition and religion.

The very idea of God, of a deity, at least in the major monotheistic religions, is inherently authoritarian. God is the creator of the universe. He is all-powerful and all-knowing: he sees all and knows all, including what we are all thinking. (and in these religions, he is a he, not a she). This notion of an omnipotent and omniscient god is authoritarian: God is Authority; he is the ultimate Boss, the ultimate King, and it is everybody’s duty to obey him, on pain of everlasting damnation. According to the anarchists, belief in God tends to create and to reinforce authoritarian modes of thought and behavior among the people: obedience is blessed, good; defiance—rebellion, revolution—is sin, bad.

Because of its authoritarian nature, religion, certainly the organized churches, encourages people to be dependent on authority for their ideas, not only concerning questions of religion, but also concerning those of morality and politics. Members of ecclesiastical hierarchies, from parish priest or minister on up, tend to have great authority in religious communities, discouraging independent, let alone radical and revolutionary, ideas.

Religion has almost invariably been a prop of class society. Throughout history, religious institutions have sought to strengthen themselves by allying with the ruling classes and institutions of class/ authoritarian societies and, at the same time, defending those classes and institutions from revolt from below. For their part, the ruling powers have legitimized and protected themselves from internal and external threats by clothing themselves in religious garb and by supporting religion and the major churches. Religion has thus been an integral part of the authoritarian, hierarchical structure of class societies. In fact, the churches have often been among the most reactionary forces within the specific societies of which they are a part, setting themselves in opposition to all change, even to relatively mild reforms that represent little or no threat to the social systems they are defending.

Religion tells people not to fight for their freedom here and now. Salvation, according to most religious dogmas, is not to be sought in the present and in the material world, but “beyond” this world, either in an after-life, as in Christianity and Islam, at the “end of time,” as in messianic Judaism, or in some sort of blessed state that exists— and that a devoted few might reach—outside of our usual conceptions of time and space, as in Buddhism and other eastern religions. As a result, religion has served to give people a false sense of comfort and solace, some sense of fulfillment, under oppressive social conditions, rather than urging them to eliminate those conditions by overthrowing the social system that gives rise to them. Religion, in sum, dulls the pain of people’s oppressed condition and blunts their struggle to end it. If, in contrast, people were to realize that this is the only world there is and this the only life they have, they would be much more likely to struggle to improve their lives in the here and now. It was in this sense that Karl Marx referred to religion as the “opiate of the people.”

Religion lends itself to fanaticism, the desire to impose one’s ideas on others by force. Since religious beliefs are not testable, they are not responsive to ordinary logic and to argument. They are accepted on faith and as The Truth, that is, as absolutely true. Moreover, religious ideas deal with, and claim to answer, fundamental metaphysical questions, such as morality and the salvation of individuals and all humanity. They also tend to be passed along by, and to be dependent on, authority, (priests, tradition, dogma, etc.). As a result of these (and perhaps other) characteristics of religion, many religious individuals, seeking security in an often frightening world, develop literalist, fundamentalist, and militant approaches to their faiths. If our beliefs are True, this type of thinking goes, it is true for everybody and in all times and places. And if this is so, it is our duty to force others to accept our beliefs, or failing this, to compel them to live under the strictures of our religion.

**Comment by EsmailELBoBDev2** [comment]
All I understand is that you hate religions? but for me I will stand by mine. I kinda understand if one who created religion is another person to get "power" as you stated but what Allah will gain from it? nothing.

NOTE: god is he because at least in Arabic the "he" هو can actually describe both Men and Women. Allah (the god in my religion) is an entity (not male or female) and in quaran it says ليس في مثله شئ or nothing like him. so no matter how much you think you will never get what god (Allah) looks like because our brain never seen something similar to him.

And finally lets agree to disagree you will never understand my point of view that I respect my (and your) creator Allah.

**Comment by EsmailELBoBDev2** [comment]
And going to say it again, LGBT does not make sense. If Allah wanted it to not be a sin trust me we would be fine making biological babies when two men/women get married.

The thing is I want you and hopefully to all understand, Humans are animals and animals want to reproduce and fill their needs. 
![image](https://github.com/Metastem/wikiless/assets/28893833/3f043f95-655b-4e9a-b2e8-64ea42c50e6d)

As you see first need is physiological which includes sex for making babies so life can goes on. At least if you are not religious I'm sure you heard about Adam and Eve! if it's ok to be gay why would not Allah just make another Adam for Adam? 

What I'm trying to say, (back to my point) that we need to fill our needs and it includes making babies so humans can survive for another decade. Sure we got sperm banks but still it's not NORMAL.

**Comment by EsmailELBoBDev2** [comment]
So logical or religion reasons. I will refuse the *act* not the person. so yes I'm not supporting it because I see it nonsense. Hate me, block me. Trust me, I won't lose my faith in Allah for bunch internet downvotes.

Salam, my friend!

**Comment by EsmailELBoBDev2** [comment]
PS: last note, religion depends on brain too. if you observe the universe you will find Allah creations everywhere. So yes, actually when you think, you will find Allah (just like me, I used to not believe in Allah too but I searched and found my answer) so it's thinking indeed

**Comment by Metastem** [comment]
> All I understand is that you hate religions? but for me I will stand by mine. I kinda understand if one who created religion is another person to get "power" as you stated but what Allah will gain from it? nothing.
> 
> NOTE: god is he because at least in Arabic the "he" هو can actually describe both Men and Women. Allah (the god in my religion) is an entity (not male or female) and in quaran it says ليس في مثله شئ or nothing like him. so no matter how much you think you will never get what god (Allah) looks like because our brain never seen something similar to him.
> 
> And finally lets agree to disagree you will never understand my point of view that I respect my (and your) creator Allah.
> 
> And going to say it again, LGBT does not make sense. If Allah wanted it to not be a sin trust me we would be fine making biological babies when two men/women get married.
> 
> The thing is I want you and hopefully to all understand, Humans are animals and animals want to reproduce and fill their needs. ![image](https://user-images.githubusercontent.com/28893833/240440396-3f043f95-655b-4e9a-b2e8-64ea42c50e6d.png)
> 
> As you see first need is physiological which includes sex for making babies so life can goes on. At least if you are not religious I'm sure you heard about Adam and Eve! if it's ok to be gay why would not Allah just make another Adam for Adam?
> 
> What I'm trying to say, (back to my point) that we need to fill our needs and it includes making babies so humans can survive for another decade. Sure we got sperm banks but still it's not NORMAL.
> 
> So logical or religion reasons. I will refuse the _act_ not the person. so yes I'm not supporting it because I see it nonsense. Hate me, block me. Trust me, I won't lose my faith in Allah for bunch internet downvotes.
> 
> PS: last note, religion depends on brain too. if you observe the universe you will find Allah creations everywhere. So yes, actually when you think, you will find Allah (just like me, I used to not believe in Allah too but I searched and found my answer) so it's thinking indeed
> 
> And no I'm not forcing my opinion in fact there is something in my religion called لكم دينكم و ليا ديني which roughly translates to, you have your beliefs and I have mine. if forcing then I would block anyone against me as some did here by blacklisting my instance.
> 
> update: shrieked my replies into one

People don't need your teachings to define what makes sense and what doesn't.  I'm not a LGBT supporter, I'm not an LGBT opponent, I'm also a normal sexual orientation person, but you are clearly discriminating against minorities, so everyone is taking an iron fist against you. All I can say is that you deserve it

**Comment by EsmailELBoBDev2** [comment]
My what now? it's science and logic. what religious in Maslow's Hierarchy of Needs, lol. Yes, you clearly not a supporter, I can see it. And I'm not discriminating people or attacking someone in specific (once again) so you can take your iron fist and shove it in your a*$

**Comment by Metastem** [comment]
> My what now? it's science and logic. what religious in Maslow's Hierarchy of Needs, lol. Yes, you clearly not a supporter, I can see it. And I'm not discriminating people or attacking someone in specific (once again) so you can take your iron fist and shove it in your a*$

You're just making personal attacks and looking for nonsensical justifications for your fascist behavior, your instance will be permanently deleted here, and I'm happy to see if you block your instance from users, it keeps people and comrades got attacked by facisits assholes like you.

**Comment by Metastem** [comment]
![20230506_220724](https://github.com/Metastem/wikiless/assets/110768529/ccb1b603-2b7e-4f17-b3a6-310e071a57f6)
![20230506_220553](https://github.com/Metastem/wikiless/assets/110768529/e9cc0dc0-e296-4a5b-9071-98017237cd5e)

**Comment by EsmailELBoBDev2** [comment]
> You're just making personal attacks and looking for nonsensical justifications for your fascist behavior, your instance will be permanently deleted here, and I'm happy to see if you block your instance from users, it keeps people and comrades got attacked away from facisits just like you.

oh my gawd, oh my gawd, I'm scared...he is removing my instance (lol) 

Dude, remove my instance or keep it or shove it into your a*$. I do not care.

**Comment by Metastem** [comment]
> > You're just making personal attacks and looking for nonsensical justifications for your fascist behavior, your instance will be permanently deleted here, and I'm happy to see if you block your instance from users, it keeps people and comrades got attacked away from facisits just like you.
> 
> oh my gawd, oh my gawd, I'm scared...he is removing my instance (lol)
> 
> Dude, remove my instance or keep it or shove it into your a*$. I do not care.
> 
> "fascist behavior" at least I do respect people religions unlike you...[#30 (comment)](https://github.com/Metastem/wikiless/issues/30#issuecomment-1560232345) so believe it or no, I support more free speech than you do.
> 
> PS: unless you are a prof star, remove the iron fist from there first!

Free speech is a lie told to us by our rulers to convince us we need to be ruled by them.
some people insist on using bigoted or otherwise oppressive language, claiming that free speech allows them to do so. Since we’ve admitted that free speech is nothing more than an insipid lie our rulers tell us in order to control us, it’s important that we reject the dishonest language of the facisits, and take a long hard look at the reasons someone would have for clinging to the state’s shrewd promises of “rights” and “freedoms” that simply don’t exist.

**Comment by EsmailELBoBDev2** [comment]
ChatGPT

**Comment by EsmailELBoBDev2** [comment]
Can we just agree to disagree? I will not back down and you won't list it back so just shut-up.

**Comment by Metastem** [comment]
> Can we just agree to disagree? I will not back down and you won't list it back so just shut-up.

How's that possible agree to disagree, I'm or We(Metastem) are ultra left wings people, and you are ultra right wings spineless liberal facisits bastards, I will shut up, but your thoughts have decided we will always against each other, and I will make sure you never come back.

**Comment by EsmailELBoBDev2** [comment]
> and I will make sure you never come back.

Are you threatening me right now?? how classy, ofc.

**Comment by sylentpunk** [comment]
Welp, this certainly revealed a lot about someone who's instances I used. What a shame.

**Comment by EsmailELBoBDev2** [comment]
> this certainly revealed a lot 

What? was it a secret that I'm Muslim?  lol

> What a shame

I'm going to say the same for you

**Comment by Metastem** [comment]
> > this certainly revealed a lot
> 
> What? was it a secret that I'm Muslim? lol
> 
> > What a shame
> 
> I'm going to say the same for you

No, we do not hate Muslims, all fake Muslims are best Muslims. lol

**Comment by EsmailELBoBDev2** [comment]
> > > this certainly revealed a lot
> > 
> > 
> > What? was it a secret that I'm Muslim? lol
> > > What a shame
> > 
> > 
> > I'm going to say the same for you
> 
> No, we do not hate Muslims, all fake Muslims are best Muslims. lol

I'm going to ignore this because we both know you are trolling.
 ___
> > What? was it a secret that I'm Muslim? lol
> 
> Your behaviour has revealed that you are not worth associating with in any capacity because you are a toxic person.
> 
> > I'm going to say the same for you
> 
> I'm sorry to hear that my love of handsome lovely boys is upsetting to you smirk

Trust me, love boys, girls or even horses. In my religion that I respect and follow. Same gender love is forbidden and I will never stop expressing my rejection of LGBT :)
