### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by rjb330** [Metastem/wikiless#8]
I've been testing out using minerva skin for mobile user agents. I got it working but the CSS is broken, even if I make it load the minerva CSS scraped from Wikipedia, SVG's doesn't load . Also dark mode wouldn't work since there is no stylesheet for mobile.

**Comment by aaferrari** [comment]
Another option would be to add this tag so that the content can adapt better on small screens:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
Then it would be a matter of adjusting the CSS to make it more responsive.

Although if you prefer to keep separate skins for mobile and desktop, in addition to Vector, Minerva and Monobook, there are also [these](https://www.mediawiki.org/wiki/Category:All_skins) (although I don't know if any of them work for mobile devices). But you must know that according to [this](https://en.wikipedia.org/wiki/Special:Version#mw-version-skin) in Wikipedia only [Cologne Blue](https://www.mediawiki.org/wiki/Skin:Cologne_Blue), [Modern](https://www.mediawiki.org/wiki/Skin:Modern) and [Timeless](https://www.mediawiki.org/wiki/Skin:Timeless) are installed (besides the already mentioned).

**Comment by xbdmHQ** [comment]
> ```
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> ```

Make a pull request

**Comment by xbdmHQ** [comment]
@Metastem This is resolved!
